# Generated by Django 5.0.4 on 2024-04-24 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante_app', '0003_usermod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usermod',
        ),
    ]
